name: SOFTURE MESSAGE BROKER - RABBIT - RELEASE NEW VERSION TO NUGET.ORG

on:
  release:
    types: [released]

jobs:
  publishing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: âš™ï¸ Install dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.100

    - name: ğŸ”— Restore dependencies
      run: dotnet restore ./API

    - name: ğŸ“‚ Create new nuget package
      run: dotnet pack --no-restore -c Release -o ./artifacts /p:PackageVersion=${{ github.ref_name }} /p:Version=${{ github.ref_name }} ./API/SOFTURE.MessageBroker.Rabbit/SOFTURE.MessageBroker.Rabbit.csproj
      continue-on-error: false

    - name: ğŸš€ Push new nuget package
      run: dotnet nuget push ./artifacts/SOFTURE.MessageBroker.Rabbit.${{ github.ref_name }}.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json